name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
      redis:
        image: redis:latest
        ports:
          - 6379:6379 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 26.10.0
      - run: npm install
      - run: npm test
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          REDIS_URL: ${{ secrets.REDIS_URL}}